version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react-i18next
    versions:
    - 11.7.0
    - 11.8.10
    - 11.8.12
    - 11.8.13
    - 11.8.14
    - 11.8.5
    - 11.8.7
    - 11.8.8
    - 11.8.9
  - dependency-name: jest-puppeteer
    versions:
    - 4.4.0
    - 5.0.0
    - 5.0.1
    - 5.0.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.5.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.7
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: i18next
    versions:
    - 19.8.5
    - 19.8.7
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.1.0
    - 20.2.1
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.0
    - 4.11.3
  - dependency-name: dompurify
    versions:
    - 2.2.6
    - 2.2.7
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
  - dependency-name: size-limit
    versions:
    - 4.10.0
    - 4.10.1
    - 4.9.1
    - 4.9.2
  - dependency-name: puppeteer
    versions:
    - 3.0.0
    - 7.1.0
    - 8.0.0
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
    - 11.0.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: terser-webpack-plugin
    versions:
    - 5.0.3
  - dependency-name: manifesto.js
    versions:
    - 4.2.1
  - dependency-name: eslint-config-airbnb
    versions:
    - 18.2.0
  - dependency-name: react-placeholder
    versions:
    - 4.0.3
  - dependency-name: redux
    versions:
    - 4.0.5
